from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 438)
        Form.setStyleSheet("background-color: rgb(246, 246, 255);\n"
                           "")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setStyleSheet("color: rgb(45, 44, 45);\n"
                                    "font: 300 17px \"Segoe UI\";")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("background-color: blue;\n"
                                      "     border-style: outset;\n"
                                      "     border-radius: 10px;\n"
                                      "     border-color: beige;\n"
                                      "    font: 300 20px \"Segoe UI\";\n"
                                      "color: white;\n"
                                      "     padding: 6px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setStyleSheet("font: 300 14px \"Segoe UI\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.verticalLayout_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Применить к модели"))

        self.pushButton_3.setIcon(QtGui.QIcon("static/export.png"))
        self.pushButton_2.setIcon(QtGui.QIcon("static/import.png"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Правило 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Правило 2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Правило 3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Правило 4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Правило 5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "a1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "b1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "c1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "d1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "a2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "b2"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "c2"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "d2"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "a3"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "b3"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "с3"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "d3"))
        self.comboBox.addItem("Максвелла")
        self.comboBox.addItem("Перевернутый   ")



class Base_Widget(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
