from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("widget_data")
        Form.resize(500, 500)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 49, 300, 300))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout1_2.addWidget(self.label_4)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout1_2.addWidget(self.lineEdit_8)
        self.verticalLayout.addLayout(self.horizontalLayout1_2)
        self.horizontalLayout1_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_5.setObjectName("horizontalLayout1_5")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout1_5.addWidget(self.label_8)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout1_5.addWidget(self.lineEdit_11)
        self.verticalLayout.addLayout(self.horizontalLayout1_5)
        self.horizontalLayout1_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_8.setObjectName("horizontalLayout1_8")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout1_8.addWidget(self.label_11)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout1_8.addWidget(self.lineEdit_14)
        self.verticalLayout.addLayout(self.horizontalLayout1_8)
        self.horizontalLayout1_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_7.setObjectName("horizontalLayout1_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout1_7.addWidget(self.label_10)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout1_7.addWidget(self.lineEdit_13)
        self.verticalLayout.addLayout(self.horizontalLayout1_7)
        self.horizontalLayout1_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_6.setObjectName("horizontalLayout1_6")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout1_6.addWidget(self.label_9)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout1_6.addWidget(self.lineEdit_12)
        self.verticalLayout.addLayout(self.horizontalLayout1_6)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout1.addWidget(self.label_2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout1.addWidget(self.lineEdit_6)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(325, -40, 300, 300))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout1_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_3.setObjectName("horizontalLayout1_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout1_3.addWidget(self.label_6)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout1_3.addWidget(self.lineEdit_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_3)
        self.horizontalLayout1_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_9.setObjectName("horizontalLayout1_9")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout1_9.addWidget(self.label_12)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout1_9.addWidget(self.lineEdit_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_9)
        self.horizontalLayout1_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_10.setObjectName("horizontalLayout1_10")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout1_10.addWidget(self.label_13)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout1_10.addWidget(self.lineEdit_16)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_10)
        self.horizontalLayout1_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_11.setObjectName("horizontalLayout1_11")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout1_11.addWidget(self.label_14)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout1_11.addWidget(self.lineEdit_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout1_11)
        self.horizontalLayout1_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_12.setObjectName("horizontalLayout1_12")
        self.verticalLayout_2.addLayout(self.horizontalLayout1_12)
        self.horizontalLayout1_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_4.setObjectName("horizontalLayout1_4")
        self.verticalLayout_2.addLayout(self.horizontalLayout1_4)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 350, 471, 24))
        self.pushButton.setObjectName("full_menu_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Параметры маятника"))
        self.label_4.setText(_translate("Form", "Масса диска"))
        self.label_8.setText(_translate("Form", "Масса оси"))
        self.label_11.setText(_translate("Form", "Радиус диска"))
        self.label_10.setText(_translate("Form", "Шаг измерений"))
        self.label_9.setText(_translate("Form", "Время измерений"))
        self.label_2.setText(_translate("Form", "Начальная координата"))
        self.label_5.setText(_translate("Form", "Параметры ген.алгоритма"))
        self.label_6.setText(_translate("Form", "Начальная скорость"))
        self.label_12.setText(_translate("Form", "Длина нити"))
        self.label_13.setText(_translate("Form", "Количество особей"))
        self.label_14.setText(_translate("Form", "Количество поколений"))
        self.pushButton.setText(_translate("Form", "Верхняя граница желаемой траектории"))

class Data_Widget(QtWidgets.QWidget, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)